### ISSUE TITLE
Add assertions for booleans

### ISSUE THREAD

**Issue by antoinemarechal** [petdance/carp-assert-more#29]
Hello,

I recently started to use this module to perform validations but when there are no helper subroutines that matches, I fall back to boolean based assertions with one of the below example constructs:

```
assert_is(all { ref($_) eq 'RegExp' } @array, !!1);

assert_fail("Directory [$dir] does not exist') if !-d $dir;
```
While those constructs work, they could be pleasantly be replaced by some new subroutines like `assert_true` and `assert_false`.

Or maybe should I use the `assert` from `Carp::Assert` in that case ? (though I'd rather avoid the additional import everywhere)

**Comment by petdance** [comment]
I'm not understanding what you'd like those two examples to be?

Something like?

```perl
assert_all { ref($_) eq 'RegExp' } @array, 'All elements are regexes';
```

**Comment by petdance** [comment]
Or is it just that you want an equivalent of `Carp::Assert::assert` in Carp::Assert::More?

**Comment by antoinemarechal** [comment]
Sorry that it wasn't clear. Those examples are what I'm currently writing. I was suggesting the addition of new subroutines to sweeten those forms. Taking back the examples, we could have something like:
```
assert_true(all { ref($_) eq 'RegExp' } @array);
assert_false(-d $dir, "Directory [$dir] does not exist");
```

Having an `assert` would fit too, but as it already exists in `Carp::Assert`, I would totally get if you tell me to use that module for that purpose.

**Comment by petdance** [comment]
So really you just want to be able to get `assert` without having to do `use Carp::Assert`. That should be doable.

**Comment by petdance** [comment]
Version 2.6.0 that I am putting out in a few minutes has `assert` in it now.
